import './App.css';
import Form from './Components/Forms';
import InputText from './Components/Forms/InputText';
import Buttom from './Components/Forms/Button';
import SectionContainer from './Components/SectionContainer';
import { useState } from 'react';
import MainTitle from './Components/MainTitle';
import TextArea from './Components/TextArea';
import ImageDisplay from './Components/ImageDisplay';
import { generateItem, generateItemSurprise } from './Service/axiosService';
import Header from './Header';




function App() {
  const [iteminput, setiteminput] = useState("")
  const [item, setitem] = useState(null)
  const [loading, setloading] = useState(false)
  function submit(e){
    e.preventDefault()
    setloading(true)
    setitem(null)
    generateItem(iteminput).then((data)=>{
      setloading(false)
      setitem(data)
      console.log(data)
    })
  }

  function submitSurprise(e){
    e.preventDefault()
    setloading(true)
    setitem(null)
    generateItemSurprise().then((data)=>{
      setloading(false)
      setitem(data)
      console.log(data)
    })
  }
  return (
    <main>
      <Header/>
      <SectionContainer>
        <MainTitle>Magic Items Generator</MainTitle>
        <Form>
          <InputText placeholder={"Insert a magic item"} onChange={setiteminput}/>
          <Buttom text={"Submit"} onClick={submit} />
          <Buttom text={"Surprise me"} onClick={submitSurprise} />
        </Form>
        {loading && <h2>Loading...</h2>}
      </SectionContainer>

      {item && <SectionContainer>
        <MainTitle>Item: </MainTitle>
        <ImageDisplay alt={"Image generated by dall-e 3"} src={item.itemUrl} />
        <TextArea title={"Visual Description"} text={item.visual} />
        <TextArea title={"Sheet (adapted for D&D 5e)"} text={item.sheet} />
      </SectionContainer>}
    </main>
  );
}

export default App;
